version: '3'

services:
  app:
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
      - redis
    build:
      context: .
    volumes:
      - ./:/code:cached
    ports:
      - ${PORT:-8000}:${PORT:-8000}

  
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      DJANGO_DB: ${DJANGO_DB:-tau_db}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-tau_db}
      DJANGO_DB_PW: ${DJANGO_DB_PW}

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  postgres-data:
