site_name: tau
site_description: Twith API Unifier
repo_url: https://github.com/Team-TAU/tau
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/finitesingularity">finitesingularity</a>.
dev_addr: 0.0.0.0:8001

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash

nav:
  - Home: 'index.md'
  - Getting Started:
    - Enviromental Options: 'env_options.md'
  - API:
    - Authentication: 'api/authentication.md'
    - V1: 'api/v1.md'
